version: "2"

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - revive
    - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming

run:
  timeout: 5m
