version: "2"

formatters:
  enable:
    - gofumpt
  exclusions:
    paths:
      - site/node_modules

linters:
  enable:
    - revive
    - errcheck
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
  exclusions:
    paths:
      - site/node_modules

run:
  timeout: 5m
